language: ruby

bundler_args: --without development

services:
  - memcached

before_script:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

rvm:
  - "1.9.3"
  - "2.0.0"
  
git:
  submodules: false
