language: ruby

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      elasticsearch

env:
  global:
    - ROOMS_DB_USER=root
    - ROOMS_DB_DATABASE=nyu_rooms_test
    - ROOMS_DB_HOST=localhost
    - ROOMS_SECRET_TOKEN=1234
    - ROOMS_COOKIE_DOMAIN=.local
    - LOGIN_URL=https://dev.login.library.nyu.edu
    - SSO_LOGOUT_PATH=/logout

before_script:
  - mysql -e 'create database nyu_rooms_test;'
  - bundle exec rake db:schema:load

rvm:
  - 2.2.6
  - 2.3.3

notifications:
  email:
    - lib-webservices@nyu.edu

sudo: false
