language: ruby

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch

env:
  global:
    - ROOMS_DB_USER=root
    - ROOMS_DB_DATABASE=nyu_rooms_test
    - ROOMS_DB_HOST=localhost
    - ROOMS_SECRET_TOKEN=1234
    - ROOMS_COOKIE_DOMAIN=.local
    - LOGIN_URL=https://dev.login.library.nyu.edu
    - SSO_LOGOUT_PATH=/logout

rvm:
  - 2.2.6
  - 2.3.3

notifications:
  email:
    - lib-webservices@nyu.edu

sudo: required

cache: bundler

install:
  - bundle install --path vendor/bundle

before_script:
  - mysql -e 'create database nyu_rooms_test;'
  - bundle exec rake db:schema:load

script:
  - elasticsearch --version
  - sudo chmod 775 /etc/elasticsearch/scripts
  - SERVER=launch TEST_CLUSTER_COMMAND=/usr/local/bin/elasticsearch TEST_CLUSTER_PARAMS='-Des.default.path.conf=/etc/elasticsearch/ -Des.default.path.logs=/var/log/elasticsearch/' bundle exec rake
