ROOMS_DB_HOST: db

ROOMS_ROLES_ADMIN:
  - superuser
  - ny_admin
  - shanghai_admin

ROOMS_DEFAULT_ADMINS:
  - admin

ROOMS_ROLES_AUTHORIZED:
  shanghai_undergraduate:
    - '0'
  ny_undergraduate:
    - '1'
    - '2'
  ny_graduate:
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'

LOGIN_COOKIE_DOMAIN: '.library.nyu.edu'
LOGIN_URL: https://dev.login.library.nyu.edu
PASSIVE_LOGIN_PATH: /login/passive
SSO_LOGOUT_PATH: /logout

ROOMS_DEV_ELASTICSEARCH_URL: http://elasticsearch:9200
