version: '3'

services:
  
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: "tail -f /dev/null"
    depends_on:
      - setup_dbs

  test:
    build: .
    volumes:
      - .:/app
    environment:
      RAILS_ENV: test
      SERVER: launch
      ROOMS_DB_HOST: db
      # TEST_CLUSTER_COMMAND: 'elasticsearch-2.4.3/bin/elasticsearch'
      # TEST_CLUSTER_PARAMS: '-Des.default.path.conf=elasticsearch-2.4.3/config/ -Des.default.path.logs=/var/log/elasticsearch/'
    command: "tail -f /dev/null"
    depends_on:
      - setup_dbs

  setup_dbs:
    build: .
    volumes:
      - .:/app
    environment:
      ROOMS_DB_HOST: db
    command: bash -c "sleep 5; rake db:setup"
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:2.4.3
    ports:
      - "9200:9200"
