version: '3.7'
x-build: &build
  build:
    context: .
    cache_from:
      - rooms
      - $ECR_DOMAIN/rooms
      - $ECR_DOMAIN/rooms:$BRANCH_NO_SLASH
  image: rooms
x-test-env: &test-env
  <<: *build
  environment:
    RAILS_ENV: test
    ROOMS_DB_DATABASE: rooms_test
    BRANCH_NO_SLASH:
  env_file:
    - test.env
x-dev-env: &dev-env
  <<: *build
  env_file:
    - test.env

services:
  dev:
    <<: *dev-env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: ["/tmp/wait-for-it.sh", "db:3306", "elasticsearch:9200", "--", "bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - setup_dev
    # volumes:
    #   - ./:/app

  setup_dev:
    <<: *dev-env
    command: >
      bash -c "bundle exec rake db:setup
      && rake environment elasticsearch:import:model CLASS='Room' FORCE=true
      && rake environment elasticsearch:import:model CLASS='Reservation' FORCE=true"
    depends_on:
      - db

  test:
    <<: *test-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "elasticsearch:9200", "--", "bundle", "exec", "rake"]
    depends_on:
      - setup_test

  setup_test:
    <<: *test-env
    command: >
      bash -c "sleep 5; rake db:setup"
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:2.4.3
    ports:
      - "9200:9200"
