version: '3.7'

services:

  dev:
    tty: true
    stdin_open: true
    build: .
    image: rooms
    volumes:
      - ./app:/app/app
    ports:
      - "3000:3000"
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "elasticsearch:9200", "--", "bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - setup_dev

  setup_dev:
    build: .
    image: rooms
    env_file:
      - test.env
    command: >
      bash -c "bundle exec rake db:setup
      && rake environment elasticsearch:import:model CLASS='Room' FORCE=true
      && rake environment elasticsearch:import:model CLASS='Reservation' FORCE=true"
    depends_on:
      - db

  test:
    build: .
    image: rooms
    environment:
      RAILS_ENV: test
      ROOMS_DB_DATABASE: rooms_test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "elasticsearch:9200", "--", "bundle", "exec", "rake"]
    depends_on:
      - setup_test

  setup_test:
    build: .
    image: rooms
    environment:
      RAILS_ENV: test
      ROOMS_DB_DATABASE: rooms_test
    env_file:
      - test.env
    command: >
      bash -c "sleep 5; rake db:setup"
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:2.4.3
    ports:
      - "9200:9200"
