docker-defaults: &docker-defaults
  docker:
    - image: docker:18.03.0-ce-git
  working_directory: ~/app

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start container and run tests
          command: |
            docker-compose run test rake

  deploy-dev:
    <<: *docker-defaults
    steps:
      - deploy:
          name: Deploy into development via Jenkins
          command: |
            curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Room%20Reservation/job/Room%20Reservation%20Development%20Deploy/build/api

  deploy-prod:
    <<: *docker-defaults
    steps:
      - deploy:
          name: Deploy into production via Jenkins
          command: |
            curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Room%20Reservation/job/Room%20Reservation%20Production%20Deploy/build/api

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
              - test
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
              - test
          filters:
            branches:
              only: master
