docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
      environment:
        - IMAGE_NAME=rooms
        - COMPOSE_PROJECT_NAME=rooms
  working_directory: ~/app

auth_quay: &auth_quay
  run:
    name: Authenticate Quay
    command: |
      docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build dev
      docker-compose -f docker-compose.build.yml build

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker pull quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH} || docker pull quay.io/nyulibraries/${IMAGE_NAME}:latest

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:latest
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker push quay.io/nyulibraries/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_quay
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *push_docker
      # - run:
      #     name: Run tests
      #     command: |
      #       export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      #       docker-compose run test
      # - run:
      #     name: Get Junit tests from stopped container
      #     when: always
      #     command: docker cp rooms_test_run_1:/app/test-results .
      - store_test_results:
          path: ~/app/test-results
      - store_artifacts:
          path: ~/app/test-results

  deploy-dev:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - deploy:
          name: Deploy into development via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Room%20Reservation/job/Room%20Reservation%20Development%20Deploy/build/api

  deploy-prod:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - deploy:
          name: Deploy into production via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Room%20Reservation/job/Room%20Reservation%20Production%20Deploy/build/api

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
              - test
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          requires:
              - test
          filters:
            branches:
              only: master
