mysql2: &mysql2
  adapter: mysql2
  encoding: utf8


development: &development
  <<: *mysql2
  host: <%= ENV['ROOMS_DB_HOST'] %>
  database: <%= ENV['ROOMS_DB_DATABASE'] %>
  username: <%= ENV['ROOMS_DB_USER'] %>
  password: <%= ENV['ROOMS_DB_PASSWORD'] %>

test:
  <<: *development

qa:
  <<: *development

staging:
  <<: *development

production:
  <<: *development
