# External config to match actions to sprite image names
destroy: "icons-famfamfam-cross"
date: "icons-famfamfam-date"
resend: "icons-famfamfam-email_go"
warning: "icons-famfamfam-error"
photo: "icons-famfamfam-photo"
sortable: "icon-chevron-down icon-white"
sort_asc: "icon-chevron-down icon-white"
sort_desc: "icon-chevron-up icon-white"