# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06c600933d898622ca8a6c042e0ba2bb2256c7e7ddbe1f56e47ba508ce9f854b44cface77760eff46b4961e2b668b0582fcb447c5ef7f16ec641f1a618c6ed5a

test:
  secret_key_base: d26482b40507b7ed86773278f006b371da2972dc89ae30604d786ea90beff241f75ae8db1f20ff6839dec71f7e6750135abca5156145ea61ebd2196df94af9ca

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

qa:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
