# Default public settings

databases:
  password:
  username: root
  database: nyu_rooms_test
  host: localhost

capistrano:
  server:
  user:
  path:
  scm_username:

newrelic:
  api_key:
  app_name: ''

login:
  default_admins: ['admin']
  pds_url: ""
  calling_system: ""

# A dummy secret token for dev sessions and public consumption

secret_token: 'dd6f1b6faf2511a744f3f08644e76edcb6be01d7019a6e62947e3a76a2c5f1ea7f3206af6bd0409ed222a56b2a53788da8de1d3528547889cc59c7dbc27f4503'

cookie:
  domain: ".local"

elasticsearch:
  bonsai:
    url: http://localhost:9200

roles:
  admin:
    - superuser
    - ny_admin
    - shanghai_admin
  authorized:
    shanghai_undergraduate:
      - "0"
    ny_undergraduate:
      - "1"
      - "2"
    ny_graduate:
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"

institutions:
  NYU:
    ip_addresses:
      - 127.0.0.1
  NYUAD:
    ip_addresses:
      - 127.0.0.1
  NYUSH:
    ip_addresses:
      - 127.0.0.1
  NYSID:
    ip_addresses:
      - 127.0.0.1
  HSL:
    ip_addresses:
      - 127.0.0.1
  CU:
    ip_addresses:
      - 127.0.0.1
  NS:
    ip_addresses:
      - 127.0.0.1
